version: 2
project_name: gopro-yank
builds:
  - main: ./cmd/gopro-yank
    binary: gopro-yank
    env: [CGO_ENABLED=0]
    goos: [darwin, linux, windows]
    goarch: [arm64, amd64]
    flags: [-trimpath]
    ldflags: ["-s -w -X main.version={{ .Version }}"]
archives:
  - name_template: gopro-yank_{{ .Os }}_{{ .Arch }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE]
snapshot:
  version_template: '{{ .Env.RELEASE_VERSION }}'
changelog:
  disable: true
